blacklist:
# LOOK IN https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#Items deemed to rare to sell
   - CREEPER_HEAD
   - DRAGON_HEAD
   - DRAGON_WALL_HEAD
   - ZOMBIE_HEAD
   - ZOMBIE_WALL_HEAD
   - SKELETON_SKULL
   - SKELETON_WALL_SKULL
   - WITHER_SKELETON_SKULL
   - WITHER_SKELETON_WALL_SKULL
   
   - DRAGON_EGG
   - ELYTRA
   - EXPERIENCE_BOTTLE
   - SPONGE
   - WET_SPONGE
   - TRIDENT
   - NAUTILUS_SHELL
   - HEART_OF_THE_SEA
   - CONDUIT
   - NETHER_STAR
   - BEACON
   
      
   - MUSIC_DISC_11 	 
   - MUSIC_DISC_13 	 
   - MUSIC_DISC_BLOCKS 	 
   - MUSIC_DISC_CAT 	 
   - MUSIC_DISC_CHIRP 	 
   - MUSIC_DISC_FAR 	 
   - MUSIC_DISC_MALL 	 
   - MUSIC_DISC_MELLOHI 	 
   - MUSIC_DISC_STAL 	 
   - MUSIC_DISC_STRAD 	 
   - MUSIC_DISC_WAIT 	 
   - MUSIC_DISC_WARD
   
   - BLACK_SHULKER_BOX
   - BLUE_SHULKER_BOX
   - BROWN_SHULKER_BOX
   - CYAN_SHULKER_BOX
   - GRAY_SHULKER_BOX
   - GREEN_SHULKER_BOX
   - LIGHT_BLUE_SHULKER_BOX
   - LIGHT_GRAY_SHULKER_BOX
   - LIME_SHULKER_BOX
   - MAGENTA_SHULKER_BOX
   - ORANGE_SHULKER_BOX
   - PINK_SHULKER_BOX
   - PURPLE_SHULKER_BOX
   - RED_SHULKER_BOX
   - SHULKER_BOX
   - SHULKER_SHELL
   - WHITE_SHULKER_BOX
   - YELLOW_SHULKER_BOX
deafultprice: 300
sellmultipier: 1.25
buymultipier: 0.50
marketfee: 10